version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo === Installing Dependencies ===
      - npm install
  post_build:
    commands:
      - echo === Building the App ===
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build